/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.EstadisticasDAO;
import Modelo.Usuario; 
import Modelo.DatoGrafico;
import util.GeneradorGraficos;
import java.awt.BorderLayout;
import java.io.File;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartPanel;

public class EstadisticasArticulosStock extends javax.swing.JFrame {

    private final EstadisticasDAO dao = new EstadisticasDAO();
    private final GeneradorGraficos generador = new GeneradorGraficos();
    private Usuario usuarioActual; 
    
    // Variable para guardar el gráfico actual y poder exportarlo luego
    private ChartPanel panelGraficoActual;

    public EstadisticasArticulosStock(Usuario usuario) {
        initComponents(); // Generado por NetBeans
        this.setResizable(false);
        this.usuarioActual = usuario; 
        // Eventos
        bCargar.addActionListener(e -> cargarGrafico());
        bExportar.addActionListener(e -> exportarGrafico());
    }

   private void cargarGrafico() {

    System.out.println("--- Iniciando cargarGrafico() ---");

    

    try {

        List<DatoGrafico> datos = dao.obtenerTopStock(9999, true); // Si pasas 0, traes todos

        

        System.out.println("Datos obtenidos: " + datos.size());

        

        if (datos.isEmpty()) {

            JOptionPane.showMessageDialog(this, "No hay datos para mostrar.");

            return;

        }

        

        // --- 1. Calcular la altura dinámica del gráfico ---

        // Asumimos 30 píxeles por artículo + un margen para el título/ejes

        final int ALTURA_ESTANDAR = 350; // Altura mínima de inicio

        final int PIXELES_POR_BARRA = 30; 

        

        int alturaCalculada = Math.max(

            ALTURA_ESTANDAR, // Altura mínima

            (datos.size() * PIXELES_POR_BARRA) + 100 // Altura dinámica

        );



        // 2. Generar el panel del gráfico

        System.out.println("Generando gráfico...");

        panelGraficoActual = generador.crearGraficoBarras(datos, "Estadística de las cantidades de Bienes Mobiliarios");



        // Establecer el tamaño preferido del panel del gráfico

        panelGraficoActual.setPreferredSize(new java.awt.Dimension(

            pnlContenedor.getWidth(), // Mantener el ancho del contenedor padre

            alturaCalculada // Usar la altura dinámica calculada

        ));



        // 3. Mostrar en el JPanel INTERNO (dentro del JScrollPane)

        System.out.println("Agregando al panel interno...");

        

        // El contenedor del gráfico ahora es el pnlGraficoInterno

        pnlGraficoInterno.removeAll(); 

        pnlGraficoInterno.setLayout(new BorderLayout()); // Asegurar que el panel interno use BorderLayout

        pnlGraficoInterno.add(panelGraficoActual, BorderLayout.CENTER);

        

        // 4. Refrescar el scroll y los contenedores

        pnlGraficoInterno.revalidate();

        pnlGraficoInterno.repaint();

        jScrollGrafico.revalidate(); // Refrescar el scroll para que calcule las barras

        

        System.out.println("--- Gráfico cargado con scroll ---");

        

    } catch (Exception e) {

        System.err.println("EXCEPCIÓN EN CARGAR GRAFICO:");

        e.printStackTrace();

        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());

    }


}

    private void exportarGrafico() {
        if (panelGraficoActual == null) {
            JOptionPane.showMessageDialog(this, "Primero carga un gráfico.");
            return;
        }

        JFileChooser ch = new JFileChooser();
        if (ch.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {
                File archivo = ch.getSelectedFile();
                // Asegurar extensión .pdf
                if (!archivo.getName().endsWith(".pdf")) {
                    archivo = new File(archivo.getAbsolutePath() + ".pdf");
                }
                
                generador.exportarPDF(panelGraficoActual, archivo);
                JOptionPane.showMessageDialog(this, "PDF guardado exitosamente.");
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error exportando: " + ex.getMessage());
                ex.printStackTrace();
            }
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlContenedor = new javax.swing.JPanel();
        pnlGraficoInterno = new javax.swing.JPanel();
        jScrollGrafico = new javax.swing.JScrollBar();
        pnlControles = new javax.swing.JPanel();
        bCargar = new javax.swing.JToggleButton();
        bExportar = new javax.swing.JToggleButton();
        bVolver = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        pnlContenedor.setBackground(new java.awt.Color(255, 255, 255));
        pnlContenedor.setLayout(new java.awt.BorderLayout());

        pnlGraficoInterno.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlGraficoInternoLayout = new javax.swing.GroupLayout(pnlGraficoInterno);
        pnlGraficoInterno.setLayout(pnlGraficoInternoLayout);
        pnlGraficoInternoLayout.setHorizontalGroup(
            pnlGraficoInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlGraficoInternoLayout.setVerticalGroup(
            pnlGraficoInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
        );

        pnlContenedor.add(pnlGraficoInterno, java.awt.BorderLayout.LINE_END);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnlContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlControles.setBackground(new java.awt.Color(255, 255, 255));
        pnlControles.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 100, 5));

        bCargar.setBackground(new java.awt.Color(13, 51, 131));
        bCargar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bCargar.setForeground(new java.awt.Color(255, 255, 255));
        bCargar.setText("Cargar Gráfico");
        bCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCargarActionPerformed(evt);
            }
        });
        pnlControles.add(bCargar);

        bExportar.setBackground(new java.awt.Color(13, 51, 131));
        bExportar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bExportar.setForeground(new java.awt.Color(255, 255, 255));
        bExportar.setText("Exportar a PDF");
        pnlControles.add(bExportar);

        bVolver.setBackground(new java.awt.Color(13, 51, 131));
        bVolver.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bVolver.setForeground(new java.awt.Color(255, 255, 255));
        bVolver.setText("Volver");
        bVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVolverActionPerformed(evt);
            }
        });
        pnlControles.add(bVolver);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlControles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlControles, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCargarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bCargarActionPerformed

    private void bVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVolverActionPerformed
        // TODO add your handling code here:
        this.dispose();
        // Pasa el usuario de vuelta al menú principal
        new PanelEstadistica(this.usuarioActual).setVisible(true);
    }//GEN-LAST:event_bVolverActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton bCargar;
    private javax.swing.JToggleButton bExportar;
    private javax.swing.JToggleButton bVolver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollGrafico;
    private javax.swing.JPanel pnlContenedor;
    private javax.swing.JPanel pnlControles;
    private javax.swing.JPanel pnlGraficoInterno;
    // End of variables declaration//GEN-END:variables
}
