/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.EstadisticasDAO;
import Modelo.Usuario; 
import Modelo.DatoGrafico;
import util.GeneradorGraficos;
import java.awt.BorderLayout;
import java.io.File;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartPanel;
import Controlador.EstadisticaControlador; 
import Modelo.ValorUbicacionDTO;
import java.util.LinkedHashMap;


public class EstadisticasUbicacion extends javax.swing.JFrame {



    // 🚨 Usamos el controlador para manejar la lógica y los errores

    private final EstadisticaControlador control = new EstadisticaControlador(); 

    private final GeneradorGraficos generador = new GeneradorGraficos();

    private Usuario usuarioActual; 

    

    // Variable para guardar el gráfico actual y poder exportarlo luego

    private ChartPanel panelGraficoActual;



    public EstadisticasUbicacion(Usuario usuario) {

        initComponents(); // Generado por NetBeans

        this.setResizable(false);

        this.usuarioActual = usuario;

    }



    // El constructor por defecto es necesario si NetBeans lo usa

    public EstadisticasUbicacion() {

        initComponents();

        this.setResizable(false);

    }

   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlContenedor = new javax.swing.JPanel();
        pnlGraficoInterno = new javax.swing.JPanel();
        jScrollGrafico = new javax.swing.JScrollBar();
        pnlControles = new javax.swing.JPanel();
        bCargar = new javax.swing.JToggleButton();
        bExportar = new javax.swing.JToggleButton();
        bVolver = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        pnlContenedor.setBackground(new java.awt.Color(255, 255, 255));
        pnlContenedor.setLayout(new java.awt.BorderLayout());

        pnlGraficoInterno.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlGraficoInternoLayout = new javax.swing.GroupLayout(pnlGraficoInterno);
        pnlGraficoInterno.setLayout(pnlGraficoInternoLayout);
        pnlGraficoInternoLayout.setHorizontalGroup(
            pnlGraficoInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlGraficoInternoLayout.setVerticalGroup(
            pnlGraficoInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
        );

        pnlContenedor.add(pnlGraficoInterno, java.awt.BorderLayout.LINE_END);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnlContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlControles.setBackground(new java.awt.Color(255, 255, 255));
        pnlControles.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 100, 5));

        bCargar.setBackground(new java.awt.Color(13, 51, 131));
        bCargar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bCargar.setForeground(new java.awt.Color(255, 255, 255));
        bCargar.setText("Cargar Gráfico");
        bCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCargarActionPerformed(evt);
            }
        });
        pnlControles.add(bCargar);

        bExportar.setBackground(new java.awt.Color(13, 51, 131));
        bExportar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bExportar.setForeground(new java.awt.Color(255, 255, 255));
        bExportar.setText("Exportar a PDF");
        bExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExportarActionPerformed(evt);
            }
        });
        pnlControles.add(bExportar);

        bVolver.setBackground(new java.awt.Color(13, 51, 131));
        bVolver.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bVolver.setForeground(new java.awt.Color(255, 255, 255));
        bVolver.setText("Volver");
        bVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVolverActionPerformed(evt);
            }
        });
        pnlControles.add(bVolver);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlControles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlControles, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCargarActionPerformed
        // TODO add your handling code here:
        System.out.println("--- Iniciando cargarGraficoValorUbicacion() ---");



    try {

        // 🚨 1. Obtener datos usando el nuevo método del controlador

        List<ValorUbicacionDTO> datosDTO = control.obtenerValorPorUbicacion(); 



        

        if (datosDTO == null || datosDTO.isEmpty()) {

            JOptionPane.showMessageDialog(this, "No hay inventario valorado para generar esta estadística.");

            return;

        }



        // 🚨 2. Mapear los DTOs al formato que espera el generador

        LinkedHashMap<String, Double> mapDatos = new LinkedHashMap<>();

        for (ValorUbicacionDTO dto : datosDTO) {

            mapDatos.put(dto.getNombreUbicacion(), dto.getValorTotal());

        }

        



        // --- 3. Calcular la altura dinámica del gráfico ---

        final int ALTURA_ESTANDAR = 350; 

        final int PIXELES_POR_BARRA = 30; 

        

        int alturaCalculada = Math.max(

            ALTURA_ESTANDAR, // Altura mínima

            (mapDatos.size() * PIXELES_POR_BARRA) + 100 // Altura dinámica

        );





        // 🚨 4. Generar el panel del gráfico usando el método de Valor por Ubicación

        System.out.println("Generando gráfico de valor por ubicación...");

        panelGraficoActual = generador.crearGraficoValorPorUbicacion(

            mapDatos, 

            "Estadística de valor total del mobiliario por ubicación"

        );





        // 5. Establecer el tamaño preferido del panel del gráfico

        panelGraficoActual.setPreferredSize(new java.awt.Dimension(

            pnlContenedor.getWidth(), // Mantener el ancho del contenedor padre

            alturaCalculada // Usar la altura dinámica calculada

        ));





        // 6. Mostrar en el JPanel INTERNO (dentro del JScrollPane)

        System.out.println("Agregando al panel interno...");

        

        pnlGraficoInterno.removeAll(); 

        pnlGraficoInterno.setLayout(new BorderLayout()); 

        pnlGraficoInterno.add(panelGraficoActual, BorderLayout.CENTER);



        

        // 7. Refrescar el scroll y los contenedores

        pnlGraficoInterno.revalidate();

        pnlGraficoInterno.repaint();

        jScrollGrafico.revalidate(); 

        

        System.out.println("--- Gráfico de Valor por Ubicación cargado ---");



    } catch (Exception e) {

        System.err.println("EXCEPCIÓN EN CARGAR GRAFICO:");

        e.printStackTrace();

        // El controlador ya maneja excepciones SQL, esto captura otros errores

        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());

    }
    }//GEN-LAST:event_bCargarActionPerformed

    private void bVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVolverActionPerformed
        // TODO add your handling code here:
        this.dispose();
        // Pasa el usuario de vuelta al menú principal
        new PanelEstadistica(this.usuarioActual).setVisible(true);
    }//GEN-LAST:event_bVolverActionPerformed

    private void bExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExportarActionPerformed
        // TODO add your handling code here:
        if (panelGraficoActual == null) {

            JOptionPane.showMessageDialog(this, "Primero carga un gráfico.");

            return;

        }



        JFileChooser ch = new JFileChooser();

        if (ch.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {

            try {

                File archivo = ch.getSelectedFile();

                // Asegurar extensión .pdf

                if (!archivo.getName().endsWith(".pdf")) {

                    archivo = new File(archivo.getAbsolutePath() + ".pdf");

                }

                

                generador.exportarPDF(panelGraficoActual, archivo);

                JOptionPane.showMessageDialog(this, "PDF guardado exitosamente.");

                

            } catch (Exception ex) {

                JOptionPane.showMessageDialog(this, "Error exportando: " + ex.getMessage());

                ex.printStackTrace();

            }

        } 
    }//GEN-LAST:event_bExportarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton bCargar;
    private javax.swing.JToggleButton bExportar;
    private javax.swing.JToggleButton bVolver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollGrafico;
    private javax.swing.JPanel pnlContenedor;
    private javax.swing.JPanel pnlControles;
    private javax.swing.JPanel pnlGraficoInterno;
    // End of variables declaration//GEN-END:variables
}
